compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"

dotenv: .env
networks:
  default: development
  development:
    verify: False
  kovan:
    verify: True
  rinkeby:
    verify: True
  mainnet-fork:
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
